---

# Base Configurations
quay_name: quay
#postgresql_name: postgresql
#mysql_name: mysql
#redis_name: redis
quay_service: "{{ quay_name }}.service"
quay_server_hostname: ""
database_type: mysql

#Systemd
systemd_service_dir: /usr/lib/systemd/system
systemd_environmenfile_dir: /etc/sysconfig

# Quay
quay_image: quay.io/coreos/quay:v2.9.2
quay_config_dir: /var/lib/quay/config
quay_container_config_dir: /conf/stack
quay_storage_dir: /var/lib/quay/storage
quay_container_storage_dir: /datastorage
quay_config_owner: root
quay_config_group: root

# External Databases
postgresql_db_uri: "postgresql://{{ database_username }}:{{ database_password }}@{{ database_host }}/{{ database_name }}"
mysql_db_uri: "mysql+pymysql://{{ database_username }}:{{ database_password }}@{{ database_host }}/{{ database_name }}"

# Container Credentials
container_credentials_file: /root/.docker/config.json
container_credentials_file_content: {}
quay_registry_server: quay.io
quay_registry_auth:
quay_registry_email:


# SSL
quay_ssl_enable: True
quay_ssl_key_file:
quay_ssl_cert_file:
quay_ssl_generate_city: Raleigh
quay_ssl_generate_state: NC
quay_ssl_generate_country: US
quay_ssl_generate_organization: Red Hat
quay_ssl_generate_organizational_unit: CoP
quay_ssl_generate_days_validity: 365
quay_ssl_generate_hostname: localhost